question_data =  [
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "The HTML5 standard was published in 2014.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "The common software-programming acronym &quot;I18N&quot; ""comes from the term &quot;Inter localization & quot;.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "To bypass US Munitions Export Laws, the creator ""of the PGP published all the source code in book form. ",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "In most programming languages, the operator ++ " "is equivalent to the statement &quot;+= 1&quot;.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "The IBM PC used an Intel 8008 microprocessor"" clocked at 4.77 MHz and 8 kilobytes of memory.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "The Windows ME operating system was released in the year 2000.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "The NVidia GTX 1080 gets its name because it can only render at a ""1920x1080 screen resolution.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "Linus Sebastian is the creator of the Linux kernel,"
                                  " which went on to be used in Linux," " Android, and Chrome OS.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "question": "The Python programming language gets its name from the British comedy"
                                  " group &quot;Monty Python.&quot;",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]}]
